config/routes.rb
require 'sidekiq/web'

Box::Application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  authenticate :user, -> user { user.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: "home#index"

  concern :permissions do
    resources :permissions, only: [:index, :create, :destroy] do
      collection do
        get :check
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :folders, only: [:show, :update] do
        scope module: :folders do
          concerns :permissions
        end
      end
      resources :uploads, only: [:create, :update, :destroy] do
        get :download
        collection do
          get :processing_status
          patch :move, :copy
        end
        scope module: :uploads do
          concerns :permissions
        end
      end
      resources :users, only: [:index, :update] do
        scope module: :users do
          resources :permissions, only: :index
          resources :conversations, only: [:index, :show, :create]
          resources :messages, only: [:create, :destroy]
          resource :friendships, only: [:create, :destroy]
          collection do
            resources :friends, only: [:index] do
              collection do
                get :online
              end
            end
            resources :search, only: [:index]
          end
        end
      end
      namespace :administration do
        resources :extension_icons, only: [:index, :create, :destroy]
      end
    end
  end

  resources :users, only: [:show, :index] do
    scope module: :users do
      resources :permissions, only: :index
      resources :purchases, only: [:index]
      resources :conversations, only: [:index, :show]
    end
  end

  resource :administration, only: [:show] do
    collection do
      get :extension_icons, :space_limits
    end
  end
end

app/views/shared/_bottom.html.slim
section#bottom
  = image_tag "social_buttons.png", height: 30, class: 'social-buttons'

app/views/shared/_current_user.html.slim
#current_user_data.hidden
  = UserSerializer.new(current_user).to_json

app/views/shared/_head.html.slim
head
  title = title
  = csrf_meta_tag
  = stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track" => true
  = javascript_include_tag 'application', "data-turbolinks-track" => true

app/views/shared/_header.html.slim
header
  .logo
    = image_tag asset_path('logo.png'), width: 400
  = render 'shared/menu'
.clear

app/views/shared/_menu.html.slim
.menu
  ul
    li
      = link_to t('.main'), root_url
    li
      a href='#' Новости
    li
      a href='#' Группы
    - if logged_in?
      li
        = link_to current_user, current_user
      li
        = link_to t('.sign_out'), destroy_user_session_path, data: { method: :delete }
      - if current_user.is_admin?
        = link_to t('.administration'), administration_path
    - else
      li
        = link_to t('.sign_up'), new_user_registration_path

app/views/shared/_rainbow_menu.html.slim
ul
  li
    | Страница
  li
    | Группы
  li
    | Новости
  li
    | Настройки
  li
    - if logged_in?
      = link_to t('.messages'), user_conversations_path(current_user)
      .messages-count
        = current_user.unread_messages_count

app/views/shared/_uploads_status.html.slim
#uploads_status ng-show="uploads.length > 0" ng-controller="UploadsStatusController"
  | Всего загружется: {{uploads.length}}
  .upload-status ng-repeat="upload in uploads"
    | {{upload.name}} - {{upload.percent}}%