config/routes.rb
require 'sidekiq/web'

Box::Application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  authenticate :user, -> user { user.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: "home#index"

  concern :permissions do
    resources :permissions, only: [:index, :create, :destroy] do
      collection do
        get :check
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :folders, only: [:show, :update] do
        scope module: :folders do
          concerns :permissions
        end
      end
      resources :uploads, only: [:create, :update, :destroy] do
        get :download
        collection do
          get :processing_status
          patch :move, :copy
        end
        scope module: :uploads do
          concerns :permissions
        end
      end
      resources :users, only: [:index, :update] do
        scope module: :users do
          resources :permissions, only: :index
          resources :conversations, only: [:index, :show, :create]
          resources :messages, only: [:create, :destroy]
          resource :friendships, only: [:create, :destroy]
          collection do
            resources :friends, only: [:index] do
              collection do
                get :online
              end
            end
            resources :search, only: [:index]
          end
        end
      end
      namespace :administration do
        resources :extension_icons, only: [:index, :create, :destroy]
      end
    end
  end

  resources :users, only: [:show, :index] do
    scope module: :users do
      resources :permissions, only: :index
      resources :purchases, only: [:index]
      resources :conversations, only: [:index, :show]
    end
  end

  resource :administration, only: [:show] do
    collection do
      get :extension_icons, :space_limits
    end
  end
end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController
  def show
  end

  def extension_icons
  end

  def space_limits
  end
end

app/controllers/api/v1/administration/extension_icons_controller.rb
class Api::V1::Administration::ExtensionIconsController < Api::V1::BaseController

  def index
    @icons = ExtensionIcon.all
    authorize @icons, class: ExtensionIcon
    render json: @icons, each_serializer: ExtensionIconSerializer
  end

  def create
    @icon = ExtensionIcon.new params[:extension_icon][:extension]
    authorize @icon
    @icon.icon = params[:extension_icon][:icon]
    @icon.save
    render json: @icon
  end

  def destroy
    @icon = ExtensionIcon.for params[:id]
    authorize @icon
    @icon.destroy
    render json: @icon
  end

end

app/views/administrations/extension_icons.html.slim
.block.extension-icons ng-controller="ExtensionIconsController"
  h1 = t 'administrations.show.extension_icons'

  .extension-icon ng-repeat="icon in icons"
    .extension
      | {{icon.extension}}
    img.icon ng-src="{{icon.url}}"
    a.delete ng-click="deleteIcon(icon)" href="" = t '.delete'
    .clear

  = text_field_tag :body, nil, 'ng-model' => 'newIcon.extension', placeholder: t('.icon_extension')
  = file_field_tag :icon, file: 'newIcon.icon', accept: 'image/png,image/gif,image/jpeg'
  = button_tag t('.save'), 'ng-click' => 'saveNewIcon()'

app/views/administrations/show.html.slim
.block
  div = link_to t('.extension_icons'), extension_icons_administration_path
  div = link_to t('.space_limits'), space_limits_administration_path

app/views/administrations/space_limits.html.slim
.block.space-limits ng-controller="SpaceLimitsController"
  h1 = t 'administrations.show.space_limits'

  .user ng-repeat="user in users"
    img.avatar src="http://placehold.it/30x30"
    .name
      | {{user.name}}
    = number_field_tag :space_limit, nil, "ng-model" => 'user.spaceLimit', placeholder: t('.available_space'), class: 'space-limit'
    a.save href="" ng-click="saveUser(user)" = t '.save'
    .clear